export const ENGLISH: any = {
  events: 'Events',
  eventsLower: 'events',
  profile: 'Profile',
  people: 'People',
  chats: 'Chats',
  logOut: 'Log out',
  eventsSearchPlaceholder: "Start entering event's name",
  recommended: 'All',
  myEvents: 'My Events',
  invites: 'Invites',
  moreInfo: 'More info',
  createEventBtn: 'Create event',
  register: 'Register',
  joinEventBtn: 'Join event',
  buyTicket: 'Buy ticket',
  invitePeople: 'Invite people',
  invite: 'Invite',
  invitePeopleToYourEvent: 'Invite people to your event',
  searchPeople: "Start entering user's name",
  futureEvents: 'Future events',
  pastEvents: 'Past events',
  nothingToShow: 'Nothing to show',
  accept: 'Accept',
  decline: 'Decline',
  accepted: 'Accepted',
  declined: 'Declined',
  editProfile: 'Edit profile',
  connections: 'Connections',
  followers: 'followers',
  followings: 'followings',
  follow: 'Follow',
  followed: 'Followed',
  fullName: 'Full name',
  userName: 'User name',
  birthday: 'Birthday',
  bio: 'Bio',
  phoneNumber: 'Phone number',
  language: 'Language',
  english: 'English',
  ukrainian: 'Ukrainian',
  save: 'Save',
  recommendedPeople: 'People',
  chat: 'Chat',
  chatThreads: 'Chat Threads',
  eventName: 'Event Name',
  date: 'Date',
  time: 'Time',
  description: 'Description',
  access: 'Access',
  public: 'Public',
  private: 'Private',
  type: 'Type',
  attendeeCall: 'Attendee call',
  consumeOnlyCall: 'Consume only call',
  paidEvent: 'Paid event',
  price: 'Price',
  enterPrice: 'Enter price',
  categories: 'Categories',
  create: 'Create',
  yourSocialMedia: 'Your social media',
  eventNamePlaceholder: 'Enter name of new event',
  eventDescriptionPlaceholder: 'Describe your event',
  free: 'Free',
}
