export const UKRAINIAN: any = {
  events: 'Події',
  eventsLower: 'подій',
  profile: 'Профіль',
  people: 'Люди',
  chats: 'Чати',
  logOut: 'Вийти',
  eventsSearchPlaceholder: "Почніть вводити назву події",
  recommended: 'Усі',
  myEvents: 'Мої події',
  invites: 'Запрошення',
  moreInfo: 'Більше',
  createEventBtn: 'Створити подію',
  register: 'Зареєструватися',
  joinEventBtn: 'Приєднатися до події',
  buyTicket: 'Купити квиток',
  invitePeople: 'Запросити людей',
  invite: 'Запросити',
  invitePeopleToYourEvent: 'Запросіть людей на вашу подію',
  searchPeople: "Почніть вводити ім'я користувача",
  futureEvents: 'Майбутні події',
  pastEvents: 'Минулі події',
  nothingToShow: 'Нічого показувати',
  accept: 'Прийняти',
  accepted: 'Прийнято',
  decline: 'Відхилити',
  declined: 'Відхилено',
  editProfile: 'Редагувати профіль',
  connections: 'Зв’язки',
  followers: 'підписників',
  followings: 'підписок',
  follow: 'Підписатися',
  followed: 'Підписано',
  fullName: 'Повне ім’я',
  userName: 'Ім’я користувача',
  birthday: 'День народження',
  bio: 'Біографія',
  phoneNumber: 'Номер телефону',
  language: 'Мова',
  english: 'Англійська',
  ukrainian: 'Українська',
  save: 'Зберегти',
  recommendedPeople: 'Користувачі',
  chat: 'Чат',
  chatThreads: 'Список чатів',
  eventName: 'Назва події',
  date: 'Дата',
  time: 'Час',
  description: 'Опис',
  access: 'Доступ',
  public: 'Публічний',
  private: 'Приватний',
  type: 'Тип',
  attendeeCall: 'Стандартний',
  consumeOnlyCall: 'Вебінар',
  paidEvent: 'Платна подія',
  price: 'Ціна',
  enterPrice: 'Введіть ціну',
  categories: 'Категорії',
  create: 'Створити',
  yourSocialMedia: 'Ваші соц мережі',
  eventNamePlaceholder: 'Введіть назву події',
  eventDescriptionPlaceholder: 'Опиши подію',
  free: 'Безкоштовно'
}
